name: pizza
description: "A Pizza Ordering App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.5
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  firebase_analytics: ^10.10.7
  flutter_native_splash: ^2.4.3
  readmore: ^3.0.0

dev_dependencies:
  icons_launcher: ^3.0.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/pizzas/8.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/pizzas/
    - assets/ingredients/
    - assets/logos/
    - assets/animations/
    - assets/icons/payment_methods/

